### ISSUE TITLE
name is name of scale

### ISSUE THREAD

**Issue by xtimbeau** [nrennie/PrettyCols#14]
Small issue, in `PrettyCols::scale_*` the `name` argument is the name of the palette, but `name` is also in `continuous_` or `discrete_scale` the name of the scale, causing an issue. Easy solution rename `name` to `palette` ?

**Comment by nrennie** [comment]
Thanks - this has already been mentioned in #12 . Changing `name` to `palette` may seem like the obvious solution but that introduces breaking changes for anyone who has already written code with e.g. `name = "palette_name"` in any of those functions. Instead, the `legend_name` argument is introduced for the same purpose. 

See the examples here: https://nrennie.github.io/PrettyCols/articles/using-with-ggplot2.html for changing the scale title.

**Comment by xtimbeau** [comment]
ok thanks
sorry for the double issue

Le sam. 11 févr. 2023 à 16:27, Nicola Rennie ***@***.***> a
écrit :
