### ISSUE TITLE
Contribution For PrettyCols to appear and Function in QGIS

### ISSUE THREAD

**Issue by Heed725** [nrennie/PrettyCols#23]
Hello Nicola ,

So i kinda continued and crafted an xml file basing on prettycols library which can be added into qgis as shown below gif 

I was hoping to show you so as i can be able to contribute it further to qgis style with credit of course so as people inn qgis could access it 

![Prettycols Project](https://github.com/user-attachments/assets/069684d1-e235-4bbd-be7b-30fe7f31404d)

**Comment by nrennie** [comment]
Thanks for working on this @Heed725  - it would be really great to add {PrettyCols} palettes to QGIS!

**Comment by Heed725** [comment]
You finally answered :) , Thank you, I've sent the xml file to QGIS Style for review ,I hope they would accept it and being integrated on qgis ,You can try it out on your own if you have qgis ive attached the zipped file.
[Prettycols Project.zip](https://github.com/user-attachments/files/16333556/Prettycols.Project.zip)

**Comment by Heed725** [comment]
Hello Nicole, Hopefully you're doing well, Prettycols is Officially accessible to qgis users via qgis style ,they accepted the xml and anyone can download it and use it within QGIS as link shown below

Hemed

https://plugins.qgis.org/styles/192/

**Comment by nrennie** [comment]
Excellent @Heed725 - thank you! I'll add a note to the README file of the package.
